image: 
  name: aligent/shopify-cli:latest

definitions:
  steps:
    - step: &theme-check
        name: Theme Check
        script:
          - echo "Starting THEME CHECK..."
          - ruby -v && node -v && npm -v && shopify version
          - ls -alR #list files in the current directory
          - echo -e "\nRunning shopify theme check --fail-level=$FAIL_LEVEL\n"; shopify theme check --fail-level=$FAIL_LEVEL
          - echo -e "Done THEME CHECK\n"

    - step: &deploy
        name: Deploy Theme
        script:
          - echo -e "DEPLOYING to $BITBUCKET_DEPLOYMENT_ENVIRONMENT...\n\n$ASCII_LABEL\n"
          - echo -e "shopify theme push --store=$SHOPIFY_STORE --password=$SHOPIFY_CLI_ACCESS_TOKEN --theme=$THEME_ID $THEME_PUSH_ARGS\n"
          - shopify theme push --store="$SHOPIFY_STORE" --password="$SHOPIFY_CLI_ACCESS_TOKEN" --theme="$THEME_ID" $THEME_PUSH_ARGS

pipelines:
  branches:
    staging:
      - step:
          <<: *deploy
          deployment: Staging

    production:
      - step: 
          script:
            - echo "Start of production deployment. Press DEPLOY button when you are ready."
      - step:
          <<: *deploy
          trigger: manual
          deployment: Production

  pull-requests:
    '**':  # Trigger for all branches
      - step:
          <<: *theme-check
