services:
  shopify-cli:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: "${USER_ID}"
        GROUP_ID: "${GROUP_ID}"
    container_name: shopify-cli-container
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    volumes:
      - .:/shopify
    working_dir: /shopify/theme
    env_file:
      - local.env
    entrypoint: /usr/local/bin/entrypoint.sh
    tty: true  # Keeps the container running
    stdin_open: true  # Keeps the container open for interaction
    command: ["tail", "-f", "/dev/null"]  # Ensure this keeps the container running
